Import gettext v0.21.1

diff --git a/gettext-tools/examples/hello-c++-qt/po/Makefile.am b/gettext-tools/examples/hello-c++-qt/po/Makefile.am
--- a/gettext-tools/examples/hello-c++-qt/po/Makefile.am
+++ b/gettext-tools/examples/hello-c++-qt/po/Makefile.am
@@ -104,7 +104,8 @@ SUFFIXES = .po .qm .sed .sin .nop .po-create .po-update
 # the .pot file. This eliminates the need to update the .po files when the
 # .pot file has changed, which would be troublesome if the .po files are put
 # under version control.
-.po.qm: $(srcdir)/$(DOMAIN).pot
+$(QMFILES): $(srcdir)/$(DOMAIN).pot
+.po.qm:
 	@lang=`echo $* | sed -e 's,.*/,,'`; \
 	test "$(srcdir)" = . && cdcmd="" || cdcmd="cd $(srcdir) && "; \
 	echo "$${cdcmd}rm -f $${lang}.qm && $(MSGMERGE) $(MSGMERGE_FOR_MSGFMT_OPTION) -o $${lang}.1po $${lang}.po $(DOMAIN).pot && $(GMSGFMT) -c --qt --statistics --verbose -o $${lang}.qm $${lang}.1po && rm -f $${lang}.1po"; \
@@ -293,11 +294,16 @@ EXTRA_DIST = remove-potcdate.sin LINGUAS $(POFILES) $(QMFILES)
 distdir1:
 	$(MAKE) update-po
 	$(MAKE) $(srcdir)/stamp-po
-	if test -f $(srcdir)/$(DOMAIN).pot; then \
+	@if test -f $(srcdir)/$(DOMAIN).pot; then \
 	  for file in $(DOMAIN).pot stamp-po; do \
 	    if test -f $$file; then d=.; else d=$(srcdir); fi; \
 	    cp -p $$d/$$file $(distdir)/$$file || exit 1; \
 	  done; \
+	else \
+	  case $(XGETTEXT) in \
+	    :) echo "Warning: Creating a tarball without '$(DOMAIN).pot', because a suitable 'xgettext' program was not found in PATH." 1>&2;; \
+	    *) echo "Warning: Creating a tarball without '$(DOMAIN).pot', because 'xgettext' found no strings to extract. Check the POTFILES and the XGETTEXT_OPTIONS in the Makefile.am file." 1>&2;; \
+	  esac; \
 	fi
 
 update-po: Makefile
diff --git a/gettext-tools/examples/hello-sh/po/Makefile.am b/gettext-tools/examples/hello-sh/po/Makefile.am
--- a/gettext-tools/examples/hello-sh/po/Makefile.am
+++ b/gettext-tools/examples/hello-sh/po/Makefile.am
@@ -101,7 +101,8 @@ SUFFIXES = .po .gmo .sed .sin .nop .po-create .po-update
 # the .pot file. This eliminates the need to update the .po files when the
 # .pot file has changed, which would be troublesome if the .po files are put
 # under version control.
-.po.gmo: $(srcdir)/$(DOMAIN).pot
+$(GMOFILES): $(srcdir)/$(DOMAIN).pot
+.po.gmo:
 	@lang=`echo $* | sed -e 's,.*/,,'`; \
 	test "$(srcdir)" = . && cdcmd="" || cdcmd="cd $(srcdir) && "; \
 	echo "$${cdcmd}rm -f $${lang}.gmo && $(MSGMERGE) $(MSGMERGE_FOR_MSGFMT_OPTION) -o $${lang}.1po $${lang}.po $(DOMAIN).pot && $(GMSGFMT) -c --statistics --verbose -o $${lang}.gmo $${lang}.1po && rm -f $${lang}.1po"; \
@@ -352,11 +353,16 @@ EXTRA_DIST = remove-potcdate.sin LINGUAS $(POFILES) $(GMOFILES)
 distdir1:
 	$(MAKE) update-po
 	$(MAKE) $(srcdir)/stamp-po
-	if test -f $(srcdir)/$(DOMAIN).pot; then \
+	@if test -f $(srcdir)/$(DOMAIN).pot; then \
 	  for file in $(DOMAIN).pot stamp-po; do \
 	    if test -f $$file; then d=.; else d=$(srcdir); fi; \
 	    cp -p $$d/$$file $(distdir)/$$file || exit 1; \
 	  done; \
+	else \
+	  case $(XGETTEXT) in \
+	    :) echo "Warning: Creating a tarball without '$(DOMAIN).pot', because a suitable 'xgettext' program was not found in PATH." 1>&2;; \
+	    *) echo "Warning: Creating a tarball without '$(DOMAIN).pot', because 'xgettext' found no strings to extract. Check the POTFILES and the XGETTEXT_OPTIONS in the Makefile.am file." 1>&2;; \
+	  esac; \
 	fi
 
 update-po: Makefile
diff --git a/gettext-tools/tests/autopoint-3 b/gettext-tools/tests/autopoint-3
--- a/gettext-tools/tests/autopoint-3
+++ b/gettext-tools/tests/autopoint-3
@@ -3,6 +3,9 @@
 
 # Test the autopoint program, with Automake.
 
+# Note: This tests fails on Alpine Linux, because the 'gzip' binary on this
+# system does not support the '--best' option.
+
 : ${AUTOCONF=autoconf}
 ${AUTOCONF} --version >/dev/null 2>/dev/null \
   || { echo "Skipping test: autoconf not found"; Exit 77; }
@@ -57,7 +60,7 @@ AC_PROG_CC
 AM_GNU_GETTEXT([external])
 AM_GNU_GETTEXT_VERSION([$ARCHIVE_VERSION])
 
-AC_CONFIG_HEADERS([config.h])
+dnl AC_CONFIG_HEADERS([config.h])
 AC_CONFIG_FILES([Makefile])
 AC_CONFIG_FILES([po/Makefile.in])
 AC_OUTPUT
@@ -107,9 +110,11 @@ echo hello.c > po/POTFILES.in
 ${ACLOCAL} -I m4 >/dev/null 2>autopoint.err
 test $? = 0 || { cat autopoint.err; Exit 1; }
 
-: ${AUTOHEADER=autoheader}
-${AUTOHEADER} >/dev/null 2>autopoint.err
-test $? = 0 || { cat autopoint.err; Exit 1; }
+if false; then
+  : ${AUTOHEADER=autoheader}
+  ${AUTOHEADER} >/dev/null 2>autopoint.err
+  test $? = 0 || { cat autopoint.err; Exit 1; }
+fi
 
 ${AUTOCONF} >/dev/null 2>autopoint.err
 test $? = 0 || { cat autopoint.err; Exit 1; }
diff --git a/gettext-tools/tests/lang-vala b/gettext-tools/tests/lang-vala
--- a/gettext-tools/tests/lang-vala
+++ b/gettext-tools/tests/lang-vala
@@ -5,6 +5,29 @@
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: vala.
 
+# Test for presence of valac.
+(valac --version) >/dev/null 2>/dev/null
+test $? -le 1 \
+  || { echo "Skipping test: valac not found"; Exit 77; }
+
+# Test whether valac can compile a trivial program.
+cat <<\EOF > prog.vala
+int main (string[] args) {
+    return 0;
+}
+EOF
+: ${VALAC=valac}
+${VALAC} prog.vala 2>prog.err \
+  || { if grep "fatal error: 'glib\.h' file not found" < prog.err > /dev/null; then
+         echo "Skipping test: valac installation incomplete"
+         Exit 77
+       else
+         cat prog.err 1>&2
+         echo "Skipping test: valac installation does not work"
+         Exit 77
+       fi
+     }
+
 cat <<\EOF > prog.vala
 int main (string[] args) {
     Intl.setlocale (LocaleCategory.ALL, "");
@@ -15,11 +38,6 @@ int main (string[] args) {
     return 0;
 }
 EOF
-
-# Test for presence of valac.
-(valac --version) >/dev/null 2>/dev/null
-test $? -le 1 \
-  || { echo "Skipping test: valac not found"; Exit 77; }
 
 : ${VALAC=valac}
 ${VALAC} --Xcc=-DGETTEXT_PACKAGE=\"prog\" prog.vala 2>prog.err \
