Import gettext v0.20.1

diff --git a/gettext-tools/examples/po/Makefile.am b/gettext-tools/examples/po/Makefile.am
--- a/gettext-tools/examples/po/Makefile.am
+++ b/gettext-tools/examples/po/Makefile.am
@@ -1,5 +1,5 @@
 ## Makefile for the gettext-tools/examples/po subdirectory of GNU gettext
-## Copyright (C) 1995-1998, 2000-2007, 2009, 2016 Free Software Foundation,
+## Copyright (C) 1995-1998, 2000-2007, 2009, 2014, 2018-2019 Free Software Foundation,
 ## Inc.
 ##
 ## This program is free software: you can redistribute it and/or modify
@@ -13,7 +13,7 @@
 ## GNU General Public License for more details.
 ##
 ## You should have received a copy of the GNU General Public License
-## along with this program.  If not, see <http://www.gnu.org/licenses/>.
+## along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
 ## Process this file with automake to produce Makefile.in.
 
@@ -98,6 +98,10 @@ SMALLPOTS = \
 # This is a synthetic domain name.
 DOMAIN = gettext-examples
 
+# These options get passed to xgettext.
+XGETTEXT_OPTIONS = \
+  --package-name='GNU gettext'
+
 # This is the copyright holder that gets inserted into the header of the
 # $(DOMAIN).pot file.  Set this to the copyright holder of the surrounding
 # package.  (Note that the msgstr strings, extracted from the package's
@@ -122,7 +126,7 @@ COPYRIGHT_HOLDER = Yoyodyne, Inc.
 # It can be your email address, or a mailing list address where translators
 # can write to without being subscribed, or the URL of a web page through
 # which the translators can contact you.
-MSGID_BUGS_ADDRESS = bug-gnu-gettext@gnu.org
+MSGID_BUGS_ADDRESS = bug-gettext@gnu.org
 
 # This is the list of locale categories, beyond LC_MESSAGES, for which the
 # message catalogs shall be used.  It is usually empty.
@@ -152,6 +156,16 @@ DUMMYPOFILES = @DUMMYPOFILES@
 
 SUFFIXES = .po .sed .sin .nop .po-update
 
+# The .pot file, stamp-po, and .po files appear in release tarballs.
+# The GNU Coding Standards say in
+# <https://www.gnu.org/prep/standards/html_node/Makefile-Basics.html>:
+#   "GNU distributions usually contain some files which are not source files
+#    ... . Since these files normally appear in the source directory, they
+#    should always appear in the source directory, not in the build directory.
+#    So Makefile rules to update them should put the updated files in the
+#    source directory."
+# Therefore we put these files in the source directory, not the build directory.
+
 .sin.sed:
 	sed -e '/^#/d' $< > t-$@
 	mv t-$@ $@
@@ -159,28 +173,28 @@ SUFFIXES = .po .sed .sin .nop .po-update
 
 all-local: all-local-@USE_NLS@
 
-all-local-yes: stamp-po
+all-local-yes: $(srcdir)/stamp-po
 all-local-no:
 
 # $(srcdir)/$(DOMAIN).pot is only created when needed. When xgettext finds no
 # internationalized messages, no $(srcdir)/$(DOMAIN).pot is created (because
 # we don't want to bother translators with empty POT files). We assume that
 # LINGUAS is empty in this case, i.e. $(POFILES) is empty. In this case,
-# stamp-po is a nop (i.e. a phony target).
+# $(srcdir)/stamp-po is a nop (i.e. a phony target).
 
-# stamp-po is a timestamp denoting the last time at which the CATALOGS have
-# been loosely updated. Its purpose is that when a developer or translator
-# checks out the package via CVS, and the $(DOMAIN).pot file is not in CVS,
-# "make" will update the $(DOMAIN).pot and the $(CATALOGS), but subsequent
-# invocations of "make" will do nothing. This timestamp would not be necessary
-# if updating the $(CATALOGS) would always touch them; however, the rule for
-# $(POFILES) has been designed to not touch files that don't need to be
-# changed.
-stamp-po: $(srcdir)/$(DOMAIN).pot
+# $(srcdir)/stamp-po is a timestamp denoting the last time at which the CATALOGS
+# have been loosely updated. Its purpose is that when a developer or translator
+# checks out the package from a version control system, and the $(DOMAIN).pot
+# file is not under version control, "make" will update the $(DOMAIN).pot and
+# the $(CATALOGS), but subsequent invocations of "make" will do nothing. This
+# timestamp would not be necessary if updating the $(CATALOGS) would always
+# touch them; however, the rule for $(POFILES) has been designed to not touch
+# files that don't need to be changed.
+$(srcdir)/stamp-po: $(srcdir)/$(DOMAIN).pot
 	@test ! -f $(srcdir)/$(DOMAIN).pot || { \
-	  echo "touch stamp-po" && \
-	  echo timestamp > stamp-poT && \
-	  mv stamp-poT stamp-po; \
+	  echo "touch $(srcdir)/stamp-po" && \
+	  echo timestamp > $(srcdir)/stamp-poT && \
+	  mv $(srcdir)/stamp-poT $(srcdir)/stamp-po; \
 	}
 
 # Note: Target 'all' must not depend on target '$(DOMAIN).pot-update',
@@ -196,10 +210,11 @@ $(DOMAIN).pot-update: $(POTFILES_DEPS) $(SMALLPOTS) remove-potcdate.sed
 	  msgid_bugs_address='$(PACKAGE_BUGREPORT)'; \
 	fi; \
 	$(XGETTEXT) --default-domain=$(DOMAIN) \
-	  --add-comments=TRANSLATORS: $(XGETTEXT_OPTIONS) \
+	  --add-comments=TRANSLATORS: \
 	  --copyright-holder='$(COPYRIGHT_HOLDER)' \
 	  --msgid-bugs-address="$$msgid_bugs_address" \
 	  --directory='$(srcdir)' \
+	  $(XGETTEXT_OPTIONS) \
 	  $(SMALLPOTS)
 	test ! -f $(DOMAIN).po || { \
 	  if test -f $(srcdir)/$(DOMAIN).pot; then \
@@ -331,14 +346,14 @@ MOSTLYCLEANFILES += stamp-poT
 MOSTLYCLEANFILES += core core.* *.stackdump $(DOMAIN).po $(DOMAIN).1po $(DOMAIN).2po *.new.po
 MOSTLYCLEANFILES += *.o
 
-MAINTAINERCLEANFILES = stamp-po $(SMALLPOTS)
+MAINTAINERCLEANFILES = $(DOMAIN).pot stamp-po $(SMALLPOTS)
 
 EXTRA_DIST = remove-potcdate.sin xsmallpot.sh mmsmallpo.sh LINGUAS \
   $(POFILES)
 
 # Hidden from automake, but really activated. Works around an automake-1.5 bug.
 #distdir: distdir1
-distdir1:
+distdir1: $(srcdir)/$(DOMAIN).pot
 	if test -f $(srcdir)/$(DOMAIN).pot; then \
 	  for file in $(DOMAIN).pot stamp-po $(SMALLPOTS); do \
 	    if test -f $$file; then d=.; else d=$(srcdir); fi; \
@@ -358,23 +373,24 @@ update-po: Makefile
 	echo "$$lang:"; \
 	test "$(srcdir)" = . && cdcmd="" || cdcmd="cd $(srcdir) && "; \
 	echo "$${cdcmd}$(MSGMERGE) $(MSGMERGE_OPTIONS) $$lang.po $(DOMAIN).pot -o $$lang.new.po"; \
-	cd $(srcdir); \
-	if $(MSGMERGE) $(MSGMERGE_OPTIONS) $$lang.po $(DOMAIN).pot -o $$tmpdir/$$lang.new.po; then \
-	  if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
-	    rm -f $$tmpdir/$$lang.new.po; \
-	  else \
-	    if mv -f $$tmpdir/$$lang.new.po $$lang.po; then \
-	      :; \
-	    else \
-	      echo "msgmerge for $$lang.po failed: cannot move $$tmpdir/$$lang.new.po to $$lang.po" 1>&2; \
-	      exit 1; \
-	    fi; \
-	  fi; \
-	  $(MAKE) $(SMALLPOFILES_FOR_lang) LL=$$lang; \
-	else \
-	  echo "msgmerge for $$lang.po failed!" 1>&2; \
-	  rm -f $$tmpdir/$$lang.new.po; \
-	fi
+	(cd $(srcdir) && \
+	 if $(MSGMERGE) $(MSGMERGE_OPTIONS) $$lang.po $(DOMAIN).pot -o $$tmpdir/$$lang.new.po; then \
+	   if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
+	     rm -f $$tmpdir/$$lang.new.po; \
+	   else \
+	     if mv -f $$tmpdir/$$lang.new.po $$lang.po; then \
+	       :; \
+	     else \
+	       echo "msgmerge for $$lang.po failed: cannot move $$tmpdir/$$lang.new.po to $$lang.po" 1>&2; \
+	       exit 1; \
+	     fi; \
+	   fi; \
+	 else \
+	   echo "msgmerge for $$lang.po failed!" 1>&2; \
+	   rm -f $$tmpdir/$$lang.new.po; \
+	   exit 1; \
+	 fi) && \
+	$(MAKE) $(SMALLPOFILES_FOR_lang) LL=$$lang
 
 $(DUMMYPOFILES):
 
@@ -383,123 +399,123 @@ $(DUMMYPOFILES):
 # Depend on LL being set.
 
 SMALLPOFILES_FOR_lang = \
-  ../hello-c/po/$$lang.po \
-  ../hello-c-gnome/po/$$lang.po \
-  ../hello-c-gnome3/po/$$lang.po \
-  ../hello-c++/po/$$lang.po \
-  ../hello-c++-qt/po/$$lang.po \
-  ../hello-c++-kde/po/$$lang.po \
-  ../hello-c++-gnome/po/$$lang.po \
-  ../hello-c++-wxwidgets/po/$$lang.po \
-  ../hello-objc/po/$$lang.po \
-  ../hello-objc-gnustep/po/$$lang.po \
-  ../hello-objc-gnome/po/$$lang.po \
-  ../hello-sh/po/$$lang.po \
-  ../hello-python/po/$$lang.po \
-  ../hello-clisp/po/$$lang.po \
-  ../hello-librep/po/$$lang.po \
-  ../hello-guile/po/$$lang.po \
-  ../hello-smalltalk/po/$$lang.po \
-  ../hello-java/po/$$lang.po \
-  ../hello-java-awt/po/$$lang.po \
-  ../hello-java-swing/po/$$lang.po \
-  ../hello-java-qtjambi/po/$$lang.po \
-  ../hello-csharp/po/$$lang.po \
-  ../hello-csharp-forms/po/$$lang.po \
-  ../hello-gawk/po/$$lang.po \
-  ../hello-pascal/po/$$lang.po \
-  ../hello-ycp/po/$$lang.po \
-  ../hello-tcl/po/$$lang.po \
-  ../hello-tcl-tk/po/$$lang.po \
-  ../hello-perl/po/$$lang.po \
-  ../hello-php/po/$$lang.po
+  $(srcdir)/../hello-c/po/$$lang.po \
+  $(srcdir)/../hello-c-gnome/po/$$lang.po \
+  $(srcdir)/../hello-c-gnome3/po/$$lang.po \
+  $(srcdir)/../hello-c++/po/$$lang.po \
+  $(srcdir)/../hello-c++-qt/po/$$lang.po \
+  $(srcdir)/../hello-c++-kde/po/$$lang.po \
+  $(srcdir)/../hello-c++-gnome/po/$$lang.po \
+  $(srcdir)/../hello-c++-wxwidgets/po/$$lang.po \
+  $(srcdir)/../hello-objc/po/$$lang.po \
+  $(srcdir)/../hello-objc-gnustep/po/$$lang.po \
+  $(srcdir)/../hello-objc-gnome/po/$$lang.po \
+  $(srcdir)/../hello-sh/po/$$lang.po \
+  $(srcdir)/../hello-python/po/$$lang.po \
+  $(srcdir)/../hello-clisp/po/$$lang.po \
+  $(srcdir)/../hello-librep/po/$$lang.po \
+  $(srcdir)/../hello-guile/po/$$lang.po \
+  $(srcdir)/../hello-smalltalk/po/$$lang.po \
+  $(srcdir)/../hello-java/po/$$lang.po \
+  $(srcdir)/../hello-java-awt/po/$$lang.po \
+  $(srcdir)/../hello-java-swing/po/$$lang.po \
+  $(srcdir)/../hello-java-qtjambi/po/$$lang.po \
+  $(srcdir)/../hello-csharp/po/$$lang.po \
+  $(srcdir)/../hello-csharp-forms/po/$$lang.po \
+  $(srcdir)/../hello-gawk/po/$$lang.po \
+  $(srcdir)/../hello-pascal/po/$$lang.po \
+  $(srcdir)/../hello-ycp/po/$$lang.po \
+  $(srcdir)/../hello-tcl/po/$$lang.po \
+  $(srcdir)/../hello-tcl-tk/po/$$lang.po \
+  $(srcdir)/../hello-perl/po/$$lang.po \
+  $(srcdir)/../hello-php/po/$$lang.po
 
-../hello-c/po/$(LL).po: hello-c.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-c $(LL)
+$(srcdir)/../hello-c/po/$(LL).po: $(srcdir)/hello-c.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-c $(LL)
 
-../hello-c-gnome/po/$(LL).po: hello-c-gnome.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-c-gnome $(LL)
+$(srcdir)/../hello-c-gnome/po/$(LL).po: $(srcdir)/hello-c-gnome.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-c-gnome $(LL)
 
-../hello-c-gnome3/po/$(LL).po: hello-c-gnome3.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-c-gnome3 $(LL)
+$(srcdir)/../hello-c-gnome3/po/$(LL).po: $(srcdir)/hello-c-gnome3.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-c-gnome3 $(LL)
 
-../hello-c++/po/$(LL).po: hello-c++.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-c++ $(LL)
+$(srcdir)/../hello-c++/po/$(LL).po: $(srcdir)/hello-c++.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-c++ $(LL)
 
-../hello-c++-qt/po/$(LL).po: hello-c++-qt.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-c++-qt $(LL)
+$(srcdir)/../hello-c++-qt/po/$(LL).po: $(srcdir)/hello-c++-qt.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-c++-qt $(LL)
 
-../hello-c++-kde/po/$(LL).po: hello-c++-kde.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-c++-kde $(LL)
+$(srcdir)/../hello-c++-kde/po/$(LL).po: $(srcdir)/hello-c++-kde.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-c++-kde $(LL)
 
-../hello-c++-gnome/po/$(LL).po: hello-c++-gnome.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-c++-gnome $(LL)
+$(srcdir)/../hello-c++-gnome/po/$(LL).po: $(srcdir)/hello-c++-gnome.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-c++-gnome $(LL)
 
-../hello-c++-wxwidgets/po/$(LL).po: hello-c++-wxwidgets.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-c++-wxwidgets $(LL)
+$(srcdir)/../hello-c++-wxwidgets/po/$(LL).po: $(srcdir)/hello-c++-wxwidgets.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-c++-wxwidgets $(LL)
 
-../hello-objc/po/$(LL).po: hello-objc.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-objc $(LL)
+$(srcdir)/../hello-objc/po/$(LL).po: $(srcdir)/hello-objc.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-objc $(LL)
 
-../hello-objc-gnustep/po/$(LL).po: hello-objc-gnustep.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-objc-gnustep $(LL)
+$(srcdir)/../hello-objc-gnustep/po/$(LL).po: $(srcdir)/hello-objc-gnustep.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-objc-gnustep $(LL)
 
-../hello-objc-gnome/po/$(LL).po: hello-objc-gnome.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-objc-gnome $(LL)
+$(srcdir)/../hello-objc-gnome/po/$(LL).po: $(srcdir)/hello-objc-gnome.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-objc-gnome $(LL)
 
-../hello-sh/po/$(LL).po: hello-sh.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-sh $(LL)
+$(srcdir)/../hello-sh/po/$(LL).po: $(srcdir)/hello-sh.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-sh $(LL)
 
-../hello-python/po/$(LL).po: hello-python.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-python $(LL)
+$(srcdir)/../hello-python/po/$(LL).po: $(srcdir)/hello-python.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-python $(LL)
 
-../hello-clisp/po/$(LL).po: hello-clisp.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-clisp $(LL)
+$(srcdir)/../hello-clisp/po/$(LL).po: $(srcdir)/hello-clisp.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-clisp $(LL)
 
-../hello-librep/po/$(LL).po: hello-librep.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-librep $(LL)
+$(srcdir)/../hello-librep/po/$(LL).po: $(srcdir)/hello-librep.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-librep $(LL)
 
-../hello-guile/po/$(LL).po: hello-guile.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-guile $(LL)
+$(srcdir)/../hello-guile/po/$(LL).po: $(srcdir)/hello-guile.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-guile $(LL)
 
-../hello-smalltalk/po/$(LL).po: hello-smalltalk.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-smalltalk $(LL)
+$(srcdir)/../hello-smalltalk/po/$(LL).po: $(srcdir)/hello-smalltalk.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-smalltalk $(LL)
 
-../hello-java/po/$(LL).po: hello-java.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-java $(LL)
+$(srcdir)/../hello-java/po/$(LL).po: $(srcdir)/hello-java.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-java $(LL)
 
-../hello-java-awt/po/$(LL).po: hello-java-awt.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-java-awt $(LL)
+$(srcdir)/../hello-java-awt/po/$(LL).po: $(srcdir)/hello-java-awt.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-java-awt $(LL)
 
-../hello-java-swing/po/$(LL).po: hello-java-swing.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-java-swing $(LL)
+$(srcdir)/../hello-java-swing/po/$(LL).po: $(srcdir)/hello-java-swing.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-java-swing $(LL)
 
-../hello-java-qtjambi/po/$(LL).po: hello-java-qtjambi.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-java-qtjambi $(LL)
+$(srcdir)/../hello-java-qtjambi/po/$(LL).po: $(srcdir)/hello-java-qtjambi.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-java-qtjambi $(LL)
 
-../hello-csharp/po/$(LL).po: hello-csharp.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-csharp $(LL)
+$(srcdir)/../hello-csharp/po/$(LL).po: $(srcdir)/hello-csharp.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-csharp $(LL)
 
-../hello-csharp-forms/po/$(LL).po: hello-csharp-forms.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-csharp-forms $(LL)
+$(srcdir)/../hello-csharp-forms/po/$(LL).po: $(srcdir)/hello-csharp-forms.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-csharp-forms $(LL)
 
-../hello-gawk/po/$(LL).po: hello-gawk.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-gawk $(LL)
+$(srcdir)/../hello-gawk/po/$(LL).po: $(srcdir)/hello-gawk.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-gawk $(LL)
 
-../hello-pascal/po/$(LL).po: hello-pascal.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-pascal $(LL)
+$(srcdir)/../hello-pascal/po/$(LL).po: $(srcdir)/hello-pascal.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-pascal $(LL)
 
-../hello-ycp/po/$(LL).po: hello-ycp.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-ycp $(LL)
+$(srcdir)/../hello-ycp/po/$(LL).po: $(srcdir)/hello-ycp.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-ycp $(LL)
 
-../hello-tcl/po/$(LL).po: hello-tcl.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-tcl $(LL)
+$(srcdir)/../hello-tcl/po/$(LL).po: $(srcdir)/hello-tcl.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-tcl $(LL)
 
-../hello-tcl-tk/po/$(LL).po: hello-tcl-tk.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-tcl-tk $(LL)
+$(srcdir)/../hello-tcl-tk/po/$(LL).po: $(srcdir)/hello-tcl-tk.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-tcl-tk $(LL)
 
-../hello-perl/po/$(LL).po: hello-perl.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-perl $(LL)
+$(srcdir)/../hello-perl/po/$(LL).po: $(srcdir)/hello-perl.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-perl $(LL)
 
-../hello-php/po/$(LL).po: hello-php.pot $(LL).po
-	$(SHELL) mmsmallpo.sh hello-php $(LL)
+$(srcdir)/../hello-php/po/$(LL).po: $(srcdir)/hello-php.pot $(srcdir)/$(LL).po
+	cd $(srcdir) && $(SHELL) mmsmallpo.sh hello-php $(LL)
